quarkus:
  application:
    name: davon-library-system
  http:
    port: 8080
    cors:
      ~: true
      origins: "http://localhost:3000,http://localhost:8080"
      methods: "GET,PUT,POST,DELETE,OPTIONS"
      headers: "Content-Type,Authorization"
  log:
    level: INFO
    category:
      "com.davon.library": DEBUG
  smallrye-openapi:
    info-title: Davon Library System API
    info-version: 1.0.0
    info-description: REST API for the Davon Library Management System
  swagger-ui:
    always-include: true
    enable: true
