name: "n8n Workflows Backup"

on:
  schedule:
    - cron: "0 21 * * *" # Runs daily at 00:00 Turkey time (UTC+3)
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Create directories to store backups
      - name: Create workflows directory
        run: mkdir -p ./workflows

      # 3. Download all workflows from n8n REST API using JWT token authentication
      - name: Download n8n workflows
        env:
          N8N_JWT_TOKEN: ${{ secrets.N8N_JWT_TOKEN }}
          N8N_URL: ${{ secrets.N8N_URL }}
          N8N_BASIC_USER: ${{ secrets.N8N_BASIC_USER }}
          N8N_BASIC_PASS: ${{ secrets.N8N_BASIC_PASS }}
        run: |
          # Check for required credentials
          if [ -z "$N8N_JWT_TOKEN" ]; then
            echo "::error::The N8N_JWT_TOKEN secret is missing."
            exit 1
          fi

          # Normalize N8N_URL (remove trailing slash if present)
          N8N_URL="${N8N_URL%/}"

          # If Basic Auth is provided, add it
          BASIC_ARGS=()
          if [ -n "$N8N_BASIC_USER" ] && [ -n "$N8N_BASIC_PASS" ]; then
            BASIC_ARGS=( -u "$N8N_BASIC_USER:$N8N_BASIC_PASS" )
            echo "Using Basic Auth."
          fi

          # Try different API endpoints and authentication methods
          echo "Attempting to connect to n8n API..."

          # Method 1: Try JWT Bearer token with /api/v1/workflows
          echo "Method 1: JWT Bearer token with /api/v1/workflows"
          LIST_URL="$N8N_URL/api/v1/workflows"
          AUTH_HEADER="Authorization: Bearer $N8N_JWT_TOKEN"

          echo "Using JWT Bearer authentication with token: ${N8N_JWT_TOKEN:0:20}..."

          HTTP_BODY=$(curl -s --request GET \
            --url "$LIST_URL" \
            --header "$AUTH_HEADER" \
            --header 'Content-Type: application/json' \
            --write-out "%{http_code}" \
            "${BASIC_ARGS[@]}")

          HTTP_STATUS="${HTTP_BODY: -3}"
          HTTP_BODY="${HTTP_BODY%???}"

          if [[ "$HTTP_STATUS" -ge 200 && "$HTTP_STATUS" -lt 300 ]]; then
            echo "✅ Success with JWT Bearer token on /api/v1/workflows"
          else
            echo "❌ Failed with JWT Bearer token. Error: $HTTP_BODY"

            # Method 2: Try API key with /rest/workflows (legacy API)
            echo "Method 2: API key with /rest/workflows (legacy)"
            LIST_URL="$N8N_URL/rest/workflows"
            AUTH_HEADER="X-N8N-API-KEY: $N8N_JWT_TOKEN"

            HTTP_BODY=$(curl -s --request GET \
              --url "$LIST_URL" \
              --header "$AUTH_HEADER" \
              --header 'Content-Type: application/json' \
              --write-out "%{http_code}" \
              "${BASIC_ARGS[@]}")

            HTTP_STATUS="${HTTP_BODY: -3}"
            HTTP_BODY="${HTTP_BODY%???}"

            if [[ "$HTTP_STATUS" -ge 200 && "$HTTP_STATUS" -lt 300 ]]; then
              echo "✅ Success with API key on /rest/workflows"
            else
              echo "❌ Failed with API key. Error: $HTTP_BODY"

              # Method 3: Try API key with /api/v1/workflows
              echo "Method 3: API key with /api/v1/workflows"
              LIST_URL="$N8N_URL/api/v1/workflows"
              AUTH_HEADER="X-N8N-API-KEY: $N8N_JWT_TOKEN"

              HTTP_BODY=$(curl -s --request GET \
                --url "$LIST_URL" \
                --header "$AUTH_HEADER" \
                --header 'Content-Type: application/json' \
                --write-out "%{http_code}" \
                "${BASIC_ARGS[@]}")

              HTTP_STATUS="${HTTP_BODY: -3}"
              HTTP_BODY="${HTTP_BODY%???}"

              if [[ "$HTTP_STATUS" -ge 200 && "$HTTP_STATUS" -lt 300 ]]; then
                echo "✅ Success with API key on /api/v1/workflows"
              else
                echo "❌ All authentication methods failed. Last error: $HTTP_BODY"
                echo "::error::Failed to authenticate with n8n API. Please check:"
                echo "::error::1. Your N8N_JWT_TOKEN secret contains a valid JWT token"
                echo "::error::2. Your N8N_URL points to the correct n8n instance"
                echo "::error::3. Your n8n version supports the API endpoints we're trying"
                exit 1
              fi
            fi
          fi

          echo "Successfully fetched workflow list (HTTP $HTTP_STATUS)."

          # Store the working authentication method for individual workflow downloads
          WORKING_AUTH_HEADER="$AUTH_HEADER"
          WORKING_LIST_URL_BASE="${LIST_URL%/workflows}"

          # Parse the list of workflows from the .data array
          echo "$HTTP_BODY" | jq -c '.data[] | {id: .id, name: .name}' > workflows.tmp

          while IFS= read -r line; do
            id=$(echo "$line" | jq -r '.id')
            name=$(echo "$line" | jq -r '.name' | sed 's/[/:<>:"\\|?*]/_/g') # Sanitize filename
            
            echo "Downloading workflow: $name (ID: $id)"
            ITEM_URL="$WORKING_LIST_URL_BASE/workflows/$id"

            workflow_response=$(curl -s --request GET \
              --url "$ITEM_URL" \
              --header "$WORKING_AUTH_HEADER" \
              "${BASIC_ARGS[@]}")

            if echo "$workflow_response" | jq -e '.' > /dev/null 2>&1; then
              echo "$workflow_response" > "./workflows/${name} (${id}).json"
            else
              echo "Warning: Invalid JSON response for workflow $id. Skipping."
            fi
          done < workflows.tmp
          rm workflows.tmp

      # 4. Commit and push changes to the repository
      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated n8n workflow backup"
          file_pattern: "workflows/*.json"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
