name: "n8n Workflows Backup"

on:
  schedule:
    - cron: "0 21 * * *" # Runs daily at 00:00 Turkey time (UTC+3)
  workflow_dispatch:
    inputs:
      workflows:
        description: "Comma-separated workflow IDs or names to back up (optional)"
        required: false
        default: ""

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Create directories to store backups and downloaded workflows
      - name: Create workflow-backups and workflows directories
        run: mkdir -p ./workflow-backups ./workflows

      # 3. Download all workflows from n8n Public API
      - name: Download n8n workflows
        env:
          N8N_BEARER_TOKEN: ${{ secrets.N8N_BEARER_TOKEN }}
          N8N_URL: ${{ secrets.N8N_URL }}
          N8N_BASIC_USER: ${{ secrets.N8N_BASIC_USER }}
          N8N_BASIC_PASS: ${{ secrets.N8N_BASIC_PASS }}
          WORKFLOWS_INPUT: ${{ inputs.workflows }}
          WORKFLOWS_VARS: ${{ vars.N8N_WORKFLOWS }}
        run: |
          # Check for required credentials
          if [ -z "$N8N_BEARER_TOKEN" ]; then
            echo "Error: The N8N_BEARER_TOKEN secret is missing."
            exit 1
          fi

          # Normalize N8N_URL (remove trailing slash if present)
          N8N_URL="${N8N_URL%/}"

          # If Basic Auth is provided, add it
          BASIC_ARGS=()
          if [ -n "$N8N_BASIC_USER" ] && [ -n "$N8N_BASIC_PASS" ]; then
            BASIC_ARGS=( -u "$N8N_BASIC_USER:$N8N_BASIC_PASS" )
            echo "Using Basic Auth."
          fi

          LIST_URL="$N8N_URL/api/v1/workflows"
          AUTH_HEADER="Authorization: Bearer $N8N_BEARER_TOKEN"

          echo "Fetching workflows from: $LIST_URL"
          echo "Bearer Token (first 10 chars): ${N8N_BEARER_TOKEN:0:10}..."

          # Use --fail to exit with an error on HTTP failure codes (like 401 Unauthorized)
          response=$(curl -s --fail --request GET \
            --url "$LIST_URL" \
            --header "$AUTH_HEADER" \
            --header 'Content-Type: application/json' \
            "${BASIC_ARGS[@]}")

          # Check if curl command failed
          if [ $? -ne 0 ]; then
            echo "Error: Failed to fetch workflows. Check your N8N_URL and N8N_BEARER_TOKEN."
            # If a response body was returned (like a JSON error), print it.
            if [ -n "$response" ]; then
              echo "Server response: $response"
            fi
            exit 1
          fi

          # Parse the list of workflows from the .data array
          if ! echo "$response" | jq -e '.data' > /dev/null 2>&1; then
            echo "Error: Unexpected JSON structure. Expected a '.data' array."
            echo "Response: $response"
            exit 1
          fi
          echo "$response" | jq -c '.data[] | {id: .id, name: .name}' > workflows.tmp

          # Loop through each workflow and download its JSON data
          while IFS= read -r line; do
            id=$(echo "$line" | jq -r '.id')
            # Sanitize filename to remove illegal characters
            name=$(echo "$line" | jq -r '.name' | sed 's/[/:<>:"\\|?*]/_/g')
            
            echo "Downloading workflow: $name (ID: $id)"
            ITEM_URL="$N8N_URL/api/v1/workflows/$id"

            workflow_response=$(curl -s --request GET \
              --url "$ITEM_URL" \
              --header "$AUTH_HEADER" \
              "${BASIC_ARGS[@]}")

            # Validate that the response is valid JSON before saving
            if echo "$workflow_response" | jq -e '.' > /dev/null 2>&1; then
              echo "$workflow_response" > "./workflows/${name} (${id}).json"
            else
              echo "Warning: Invalid JSON response for workflow $id. Skipping."
            fi
          done < workflows.tmp
          rm workflows.tmp

      # 4. Commit and push changes to the repository
      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated n8n workflow backup"
          file_pattern: "workflows/*.json"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
